when:
  - event: push
    branch: ci

steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      environment:
        NOTION_API_KEY:
          from_secret: NOTION_API_KEY
        NOTION_DATABASE_ID:
          from_secret: NOTION_DATABASE_ID
      repo: sjc.vultrcr.com/oosa/release-docbot
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64
      registry: https://sjc.vultrcr.com/oosa
      tag: dev
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_TOKEN
    when:
      branch: ci
      event: push